CREATE TABLE EQUIPOS
(codEquipo VARCHAR2(4),
nombre VARCHAR2(30) NOT NULL,
localidad VARCHAR2(15),
CONSTRAINT PK_EQUIPOS PRIMARY KEY (codEquipo)
);
ALTER TABLE EQUIPOS ADD CONSTRAINT CK_EQUIPOS CHECK (regexp_like(codEquipo,'^[0-9]{1}'));

CREATE TABLE JUGADORES
(codJugador VARCHAR2(4),
nombre VARCHAR2(30) NOT NULL,
fechaNacimiento DATE,
demarcacion VARCHAR2(10),
codEquipo VARCHAR2(4),
CONSTRAINT PK_JUGADORES PRIMARY KEY (codJugador),
CONSTRAINT FK_JUGADORES FOREIGN KEY (codEquipo) REFERENCES EQUIPOS(codEquipo)
);

ALTER TABLE JUGADORES ADD CONSTRAINT ck_equipo CHECK (Demarcacion IN ('Portero','Defensa','Medio','Delantero'));
ALTER TABLE JUGADORES ADD CONSTRAINT nombre_Jugador CHECK(Nombre= initcap(nombre));

CREATE TABLE PARTIDOS
(codPartido VARCHAR2(4),
codEquipoLocal VARCHAR2(4),
codEquipoVisitante VARCHAR2(4),
fecha DATE,
competicion VARCHAR2(4),
jornada VARCHAR2(4),
CONSTRAINT PK_PARTIDOS PRIMARY KEY (codPartido),
CONSTRAINT FK_PARTIDOSlocales FOREIGN KEY (codEquipoLocal) REFERENCES EQUIPOS(codEquipo),
CONSTRAINT FK_PARTIDOSvisitantes FOREIGN KEY (codEquipoVisitante) REFERENCES EQUIPOS(codEquipo),
CONSTRAINT CHK_FECHA CHECK (EXTRACT(MONTH FROM FECHA)!=7 OR EXTRACT (MONTH FROM FECHA)!=8),
CONSTRAINT CHK_COMPETICION CHECK (competicion IN ('liga','copa'))
);

CREATE TABLE INCIDENCIAS
(numIncidencia VARCHAR2(6),
codPartido VARCHAR2(4),
codJugador VARCHAR2(4),
minuto VARCHAR2(2),
tipo VARCHAR2(20),
CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (numIncidencia),
CONSTRAINT FK_INCIDENCIAS1 FOREIGN KEY (codPartido) REFERENCES PARTIDOS (codPartido),
CONSTRAINT FK_INCIDENCIAS2 FOREIGN KEY (codJugador) REFERENCES JUGADORES (codJugador),
CONSTRAINT CK_INCIDENCIAS CHECK (minuto BETWEEN 1 AND 99)
);

ALTER TABLE INCIDENCIAS MODIFY tipo NOT NULL;
ALTER TABLE EQUIPOS ADD  golesMarcados VARCHAR2(3);
