CREATE TABLE Curso(
CodCurso VARCHAR2(8),
Nombre VARCHAR2(14) UNIQUE NOT NULL,
MaxAlumnos NUMBER NOT NULL,
fecha_Inicio DATE NOT NULL,
fecha_Fin DATE NOT NULL,
Num_Horas NUMBER NOT NULL,
CONSTRAINT PK_Curso PRIMARY KEY (CodCurso),
CONSTRAINT CHK_Curso CHECK (fecha_Fin > fecha_Inicio)
);

CREATE TABLE Alumno(
DNI VARCHAR2(10),
FechaNac DATE,
Sexo VARCHAR2(1),
Direccion VARCHAR2(20) NOT NULL,
Nombre VARCHAR2(14) NOT NULL,
Apellidos VARCHAR2(14),
CodCurso VARCHAR2(8),
CONSTRAINT PK_Alumno PRIMARY KEY (DNI),
CONSTRAINT FK_Alumno FOREIGN KEY(CodCurso) REFERENCES Curso(CodCurso),
CONSTRAINT CHK_Alumno CHECK (regexp_like(Sexo,'[H|M]{1}'))
);

CREATE TABLE Profesor(
DNI VARCHAR2(10),
Direccion VARCHAR2(20),
Titulacion VARCHAR2(100) NOT NULL,
Nombre VARCHAR2(14) NOT NULL,
Sueldo NUMBER(10) NOT NULL,
Codcurso VARCHAR2(8),
CONSTRAINT PK_Profesor PRIMARY KEY (DNI),
CONSTRAINT FK_Profesor FOREIGN KEY(CodCurso) REFERENCES Curso(CodCurso),
);
